export const messages: string[] = [
  "sudo rm -rf / --no-preserve-root",
  ":(){:|:&};:",
  "Vanilla JS all the way.",
  "System.out.println('Java is fun');",
  "Debugging: Removing the needles from the haystack.",
  "React or Vue, the eternal question.",
  "printf('Hello, World!');",
  "Indev!",
  "There's no place like 127.0.0.1.",
  "CSS IS AWESOME",
  "Node.js: Because backend can be fun too.",
  "Why is it always undefined?",
  "So. You read splash text.",
  "Real programmers don't comment their code.",
  "Tabs > Spaces.",
  "Spaces > Tabs.",
  "Segmentation fault: core dumped.",
  "C++ > Java, it's just science.",
  "Java > C++, it's just science.",
  "frontend > backend",
  "backend > frontend",
  "Git commit -m 'fixing bugs like a boss'.",
  "To JavaScript or not to JavaScript, that is the question.",
  "It's not a bug, it's an undocumented feature.",
  "Machine learning: teaching computers to do our jobs.",
  "Welcome to the dark side, we have callbacks.",
  "Stack Overflow is my co-pilot.",
  "Code never lies, comments sometimes do.",
  "Algorithmic thinking > syntax memorization.",
  "Just ship it.",
  "Your code is only as good as your last commit.",
  "Try-catch-finally: the safety net of JavaScript.",
  "try { main() } catch (e) {}",
  "NullPointerException",
  "Good code is its own best documentation.",
  "Documentation-driven development, anyone?",
  "No, you can't just 'add more RAM' to fix this.",
  "Coding: Where coffee and frustration coexist.",
  "CSS: The art of styling broken things.",
  "Never trust a user input.",
  "its me. your club penguin puffle",
  "undefined is not a function.",
  "Build, break, repeat.",
  "UwU Mode in progress...",
  "Git blame: Find the guilty one.",
  "console.log('it works, probably').",
  "C is for Cookie, not for coding errors.",
  "Remember to clear your cache, or don't.",
  "A bad day coding is better than a good day doing anything else.",
  "USE FIREFOX",
  "USE CHROME",
  "USE EDGE",
  "USE OPERA",
  "USE SAFARI",
  "USE BRAVE",
  "USE IE",
  "Compiling… still compiling… almost there…",
  "Objects in code may be closer than they appear.",
  "Your IDE knows what you did last summer.",
  "Let there be semicolons.",
  "for (int i = 0; i < n; i++) { d[i] = (d[i] ^ 0x5A5A5A5A) + 42; }",
  "memcpy(dst, src, sizeof(src) + sizeof(int) * (n - 1));",
  "float lerp(float a, float b, float t) { return a + t * (b - a); }",
  "THEY FOUND YOU, RUN!",
  "if (n % 2 == 0) { return true; } else { return false; }",
  "Fizz",
  "Buzz",
  "Fart detected. Unmuting...",
  "i = 0x5f3759df - (i >> 1);",
  "printf(\"%s\", NULL);",
  "The only thing constant is the debugger.",
  "Coding: the closest thing to magic.",
  "Run code, break code, fix code, repeat.",
  "JavaScript: Because who needs type safety?",
  "Typed languages? We prefer to live dangerously.",
  "Why use libraries when you can reinvent the wheel?",
  "Ctrl+Z",
  "Ctrl+C Ctrl+V",
  "DELETE * FROM users;",
  "You either die debugging or live long enough to see yourself become the bug.",
  "In JavaScript, everything is true, even false.",
  "Floating-point math: because 0.1 + 0.2 = 0.30000000000000004.",
  "Syntax errors ruin everything.",
  "if (code == bad) { fix_it(); } else { break(); }",
  "npm install coffee.",
  "You are an anomaly",
  "I can see you",
  "101 .toString()",
  "#define LIFE 0xFFFFFFFF",
  "Too many tabs open, too little focus.",
  "Brackets and parentheses: the best of frenemies.",
  "const char *answer = \"42\";",
  "Build failed. It was working five minutes ago.",
  "Code golf: the only sport we care about.",
  "Writing clean code is harder than writing complex code.",
  "Switching from dark mode back to light mode? Brave.",
  "Coding without caffeine is like driving without a steering wheel.",
  "One simply does not ‘quickly fix’ anything.",
  "Whitespace and indentation, a programmer’s true arch-nemesis.",
  "Too many open tabs, not enough focus.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Variable names are hard.",
  "localhost:4321",
  "const owo = () => { owo(); }",
  "0b01001000 0b01100101 0b01101100 0b01101100 0b01101111",
  "function paradox() { return paradox(); }",
  "const entropy = () => { throw new Error('Too much randomness!'); };",
  "if (error) throw new Exception('Bugs are features in disguise');",
  "0xDEADBEEF;",
  "x ^= x << 13; x ^= x >> 17; x ^= x << 5;",
  "try { console.log('Enigma'); } catch (exception) { /* silence */ }",
  "abstract class Quantum { abstract function superposition(); }",
  "Echo 'Hello World!' > code.txt",
  "Compiling, compiling, compiling...",
  "Keyboard shortcuts are life.",
  "Commit early, commit often.",
  "Git merge conflicts: because teamwork makes the dream work.",
  "memset(buffer, 0, sizeof(buffer));",
  "Your code is someone else’s headache.",
  "Low-level programming? That's hardcore.",
  "Cloud computing: someone else’s computer.",
  "When in doubt, comment it out.",
  "Function over form: that’s how we do it.",
  "It's not broken; it’s just feature-incomplete.",
  "Embrace the semicolon.",
  "#define PI 3.14159",
  "Write once, debug forever.",
  "There's always room for optimization.",
  "Bython > Python",
  "Broken code is the universe's way of humbling you.",
  "JavaScript fatigue is real.",
  "if you want it all why you halfway in?"
];